version: "3.9"

services:
  naming-server:
    build:
      context: ./naming-server
    container_name: naming-server
    ports:
      - "8761:8761"
    networks:
      - edagequry-net

  auth:
    build:
      context: ./auth
    container_name: auth
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
      naming-server:
        condition: service_started
    networks:
      - edagequry-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/eadgequry-auth?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=authuser
      - SPRING_DATASOURCE_PASSWORD=authpassword

  api-gatway:
    build:
      context: ./api-gatway
    container_name: api-gatway
    ports:
      - "8765:8765"
    depends_on:
      - naming-server
      - auth
    networks:
      - edagequry-net

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - edagequry-net

  mysql:
    image: mysql:8.0
    container_name: mysql-auth
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: eadgequry-auth
      MYSQL_USER: authuser
      MYSQL_PASSWORD: authpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - edagequry-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  edagequry-net:
    driver: bridge

volumes:
  mysql-data:
